[package]
name = "table"
version.workspace = true
edition.workspace = true

[dependencies]
log.workspace = true
gpui.workspace = true
gpui-component.workspace = true
regex = "1"
serde.workspace = true
serde_json.workspace = true
ai = { path = "../ai" }
diagnostics = { path = "../diagnostics" }
plugin-api = { path = "../plugin-api" }
settings = { path = "../settings" }

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
