[package]
name = "app"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
gpui.workspace = true
gpui-component.workspace = true
gpui-component-assets.workspace = true
dirs.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
window-wrapper = { path = "../window-wrapper" }
settings = { path = "../settings" }
table = { path = "../table" }
workspace = { path = "../workspace" }
