//! Theme switching: every `assets/themes/*.json` is embedded in the binary (qrate ships as a
//! bundled installer, so a loose `themes/` folder next to the exe isn't reliable), extracted
//! once to the OS data dir, and loaded through `ThemeRegistry::watch_dir` — the only public way
//! to register non-default themes. The menu then lists what the registry actually holds, so a
//! new theme file is the entire change. Selection persists via the `AppSettings` text store.

use std::{fs, path::PathBuf};

use gpui::*;
use gpui_component::{Theme, ThemeRegistry};
use schemars::JsonSchema;
use serde::Deserialize;
use settings::AppSettings;

const THEME_NAME_KEY: &str = "theme_name";

/// `AppSettings` key for the interface scale, as a whole percentage of gpui-component's 16px rem.
pub const UI_SCALE_KEY: &str = "ui_scale";

/// What Settings offers for [`UI_SCALE_KEY`]. An unset value is 100%.
pub const UI_SCALES: &[(&str, &str)] = &[
    ("90", "90%"),
    ("", "100% (default)"),
    ("110", "110%"),
    ("125", "125%"),
    ("150", "150%"),
];

/// gpui-component's own defaults for [`Theme::font_size`] and [`Theme::mono_font_size`].
const BASE_FONT_SIZE: f32 = 16.;
const BASE_MONO_FONT_SIZE: f32 = 13.;

/// Scale the rem every window lays out in (`Root` sets it from [`Theme::font_size`]), then
/// re-project the theme so gpui-base's typography tokens follow.
pub fn apply_ui_scale(cx: &mut App) {
    let percent = AppSettings::get(cx)
        .values
        .get(UI_SCALE_KEY)
        .and_then(|value| value.text().parse::<f32>().ok())
        .filter(|percent| (50.0..=200.0).contains(percent))
        .unwrap_or(100.);
    let theme = Theme::global_mut(cx);
    theme.font_size = px(BASE_FONT_SIZE * percent / 100.);
    theme.mono_font_size = px(BASE_MONO_FONT_SIZE * percent / 100.);
    let mode = theme.mode;
    Theme::change(mode, None, cx);
    cx.refresh_windows();
}

// `EMBEDDED_THEMES: &[(file_name, contents)]`, generated by `build.rs` from `assets/themes/`.
include!(concat!(env!("OUT_DIR"), "/themes.rs"));

/// Theme names for the "Theme" menu, in menu order: whatever the registry loaded, defaults
/// first, then light before dark, then by name. A theme the user dropped into the themes
/// directory by hand shows up here too.
pub fn theme_choices(cx: &App) -> Vec<SharedString> {
    ThemeRegistry::global(cx)
        .sorted_themes()
        .iter()
        .map(|config| config.name.clone())
        .collect()
}

#[derive(Clone, PartialEq, Deserialize, JsonSchema, Action)]
#[action(namespace = this_app)]
#[serde(deny_unknown_fields)]
pub struct SwitchTheme {
    pub name: String,
}

fn themes_dir() -> Option<PathBuf> {
    Some(dirs::data_local_dir()?.join("qrate").join("themes"))
}

fn extract_embedded_themes(dir: &PathBuf) -> anyhow::Result<()> {
    fs::create_dir_all(dir)?;
    for (file_name, contents) in EMBEDDED_THEMES {
        fs::write(dir.join(file_name), contents)?;
    }
    Ok(())
}

/// Runs once the registry has finished loading in the background: the menu can only list the
/// themes now that they exist, and the saved theme can only be applied now that it is registered.
fn on_themes_loaded(cx: &mut App) {
    crate::app_menus::install(cx);
    apply_saved_theme(cx);
}

/// Applies the theme saved in `AppSettings`, if any.
fn apply_saved_theme(cx: &mut App) {
    let Some(name) = AppSettings::get(cx)
        .values
        .get(THEME_NAME_KEY)
        .map(|v| v.text())
    else {
        return;
    };
    apply_theme_by_name(&name, cx);
}

fn apply_theme_by_name(name: &str, cx: &mut App) {
    if let Some(config) = ThemeRegistry::global(cx).themes().get(name).cloned() {
        Theme::global_mut(cx).apply_config(&config);
        cx.refresh_windows();
    }
}

/// Extracts the embedded themes to disk and registers the theme switcher. Call once at
/// startup, after `gpui_component::init(cx)` and after `AppSettings` has been loaded.
pub fn init(cx: &mut App) {
    apply_ui_scale(cx);
    if let Some(dir) = themes_dir() {
        match extract_embedded_themes(&dir) {
            Ok(()) => {
                if let Err(err) = ThemeRegistry::watch_dir(dir, cx, on_themes_loaded) {
                    log::error!("failed to watch the themes directory: {err}");
                }
            }
            Err(err) => log::error!("failed to extract the embedded themes: {err}"),
        }
    }

    cx.on_action(|action: &SwitchTheme, cx| {
        apply_theme_by_name(&action.name, cx);
        AppSettings::set_text(THEME_NAME_KEY, action.name.clone().into(), cx);
    });
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeSet;

    use gpui_component::ThemeConfigColors;

    /// A colour key `ThemeConfigColors` doesn't name is dropped in silence — serde has no
    /// `deny_unknown_fields` here — and the element quietly falls back to a derived colour.
    /// The schema is the list of names that actually do something.
    #[test]
    fn every_embedded_theme_colour_key_is_one_the_schema_accepts() {
        let schema = schemars::schema_for!(ThemeConfigColors).to_value();
        let known: BTreeSet<&str> = schema["properties"]
            .as_object()
            .expect("ThemeConfigColors is an object schema")
            .keys()
            .map(String::as_str)
            .collect();

        let mut unknown = Vec::new();
        for (file_name, contents) in super::EMBEDDED_THEMES {
            let set: serde_json::Value = serde_json::from_str(contents)
                .unwrap_or_else(|err| panic!("{file_name} is not valid JSON: {err}"));
            for theme in set["themes"].as_array().into_iter().flatten() {
                let name = theme["name"].as_str().unwrap_or("?");
                for key in theme["colors"]
                    .as_object()
                    .into_iter()
                    .flatten()
                    .map(|kv| kv.0)
                {
                    if !known.contains(key.as_str()) {
                        unknown.push(format!("{file_name} / {name}: {key}"));
                    }
                }
            }
        }

        assert!(
            unknown.is_empty(),
            "unknown theme colour keys: {unknown:#?}"
        );
    }
}
